### ISSUE TITLE
Drag and drop within routine editor should scroll the page when dragging outside of viewport

### ISSUE THREAD

**Issue by jhrcek** [jhrcek/sestavr#20]

**Comment by jhrcek** [comment]
@annaghi just if you're interested this is the behavior that I wanted to achieve. In the end it was relatively easy with the current version of dnd-list :smile: 

![ScrollDemo](https://user-images.githubusercontent.com/2716069/83320735-8cb25b00-a24a-11ea-85d8-128d171a5f28.gif)

**Comment by annaghi** [comment]
:+1: Thank you for letting me know, and for the gif.
That was the first part of the solution (6.0.1), next I am going to implement the auto-scrolling (7.0.0).
